"""initial schema - all 12 tables

Revision ID: fedf0444a7e8
Revises: 
Create Date: 2026-08-19 10:43:05.292518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fedf0444a7e8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', postgresql.ENUM('admin', 'nurse', 'doctor', name='user_role'), nullable=False),
    sa.Column('status', postgresql.ENUM('active', 'suspended', 'deactivated', name='user_status'), server_default='active', nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_locked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('must_change_password', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_users_created_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_role', sa.String(length=50), nullable=True),
    sa.Column('action', postgresql.ENUM('login_success', 'login_failed', 'logout', 'create', 'read', 'update', 'delete', 'soft_delete', 'approve', 'reject', 'edit_ai_output', 'export_pdf', 'hitl_resolve', name='audit_action'), nullable=False),
    sa.Column('target_entity_type', sa.String(length=100), nullable=True),
    sa.Column('target_entity_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('success', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_occurred_at'), 'audit_logs', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_entity_id'), 'audit_logs', ['target_entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_entity_type'), 'audit_logs', ['target_entity_type'], unique=False)
    op.create_table('patients',
    sa.Column('mrn', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('sex', sa.String(length=20), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('known_allergies', sa.String(length=1024), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_patients_created_by_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patients'))
    )
    op.create_index(op.f('ix_patients_full_name'), 'patients', ['full_name'], unique=False)
    op.create_index(op.f('ix_patients_mrn'), 'patients', ['mrn'], unique=True)
    op.create_table('sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_token_hash', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('session_token_hash', name=op.f('uq_sessions_session_token_hash'))
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('appointments',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('nurse_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=True),
    sa.Column('status', postgresql.ENUM('created', 'intake_in_progress', 'intake_pending_review', 'intake_complete', 'with_doctor', 'prescription_in_progress', 'prescription_pending_review', 'complete', 'cancelled', name='appointment_status'), server_default='created', nullable=False),
    sa.Column('chief_complaint', sa.String(length=512), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('intake_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('prescription_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], name=op.f('fk_appointments_doctor_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['nurse_id'], ['users.id'], name=op.f('fk_appointments_nurse_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_appointments_patient_id_patients'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointments'))
    )
    op.create_index(op.f('ix_appointments_doctor_id'), 'appointments', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_appointments_nurse_id'), 'appointments', ['nurse_id'], unique=False)
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_table('audio_recordings',
    sa.Column('appointment_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=False),
    sa.Column('input_source', postgresql.ENUM('manual_entry', 'live_recording', 'uploaded_audio', name='input_source'), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('sha256_hash', sa.String(length=64), nullable=True),
    sa.Column('processing_status', postgresql.ENUM('uploaded', 'validating', 'validation_failed', 'normalizing', 'chunking', 'transcribing', 'transcription_complete', 'transcription_failed', name='audio_processing_status'), server_default='uploaded', nullable=False),
    sa.Column('quality_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validation_failure_reason', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_audio_recordings_appointment_id_appointments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_audio_recordings_uploaded_by_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audio_recordings'))
    )
    op.create_index(op.f('ix_audio_recordings_appointment_id'), 'audio_recordings', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_audio_recordings_processing_status'), 'audio_recordings', ['processing_status'], unique=False)
    op.create_index(op.f('ix_audio_recordings_sha256_hash'), 'audio_recordings', ['sha256_hash'], unique=False)
    op.create_table('audio_chunks',
    sa.Column('audio_recording_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('start_time_seconds', sa.Float(), nullable=False),
    sa.Column('end_time_seconds', sa.Float(), nullable=False),
    sa.Column('overlap_seconds', sa.Float(), server_default='0', nullable=False),
    sa.Column('speaker_label', sa.String(length=50), nullable=True),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audio_recording_id'], ['audio_recordings.id'], name=op.f('fk_audio_chunks_audio_recording_id_audio_recordings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audio_chunks'))
    )
    op.create_index(op.f('ix_audio_chunks_audio_recording_id'), 'audio_chunks', ['audio_recording_id'], unique=False)
    op.create_table('transcripts',
    sa.Column('appointment_id', sa.UUID(), nullable=False),
    sa.Column('audio_chunk_id', sa.UUID(), nullable=True),
    sa.Column('source', postgresql.ENUM('local_asr', 'cloud_asr', 'consensus', 'human_corrected', name='transcript_source'), nullable=False),
    sa.Column('status', postgresql.ENUM('draft', 'accepted', 'flagged_for_review', 'human_reviewed', 'final', name='transcript_status'), server_default='draft', nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('quality_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('supersedes_id', sa.UUID(), nullable=True),
    sa.Column('corrected_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_transcripts_appointment_id_appointments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['audio_chunk_id'], ['audio_chunks.id'], name=op.f('fk_transcripts_audio_chunk_id_audio_chunks'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['corrected_by_id'], ['users.id'], name=op.f('fk_transcripts_corrected_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supersedes_id'], ['transcripts.id'], name=op.f('fk_transcripts_supersedes_id_transcripts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transcripts'))
    )
    op.create_index(op.f('ix_transcripts_appointment_id'), 'transcripts', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_transcripts_audio_chunk_id'), 'transcripts', ['audio_chunk_id'], unique=False)
    op.create_index(op.f('ix_transcripts_status'), 'transcripts', ['status'], unique=False)
    op.create_table('extracted_entity_sets',
    sa.Column('appointment_id', sa.UUID(), nullable=False),
    sa.Column('transcript_id', sa.UUID(), nullable=False),
    sa.Column('target_role', postgresql.ENUM('admin', 'nurse', 'doctor', name='user_role'), nullable=False),
    sa.Column('raw_entities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('validated_entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ner_model_name', sa.String(length=255), nullable=False),
    sa.Column('ner_model_version', sa.String(length=100), nullable=True),
    sa.Column('validation_passed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('validation_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('supersedes_id', sa.UUID(), nullable=True),
    sa.Column('edited_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_extracted_entity_sets_appointment_id_appointments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['edited_by_id'], ['users.id'], name=op.f('fk_extracted_entity_sets_edited_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supersedes_id'], ['extracted_entity_sets.id'], name=op.f('fk_extracted_entity_sets_supersedes_id_extracted_entity_sets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], name=op.f('fk_extracted_entity_sets_transcript_id_transcripts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extracted_entity_sets'))
    )
    op.create_index(op.f('ix_extracted_entity_sets_appointment_id'), 'extracted_entity_sets', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_extracted_entity_sets_transcript_id'), 'extracted_entity_sets', ['transcript_id'], unique=False)
    op.create_table('hitl_queue',
    sa.Column('appointment_id', sa.UUID(), nullable=False),
    sa.Column('transcript_id', sa.UUID(), nullable=True),
    sa.Column('entity_set_id', sa.UUID(), nullable=True),
    sa.Column('reason', postgresql.ENUM('low_asr_confidence', 'hallucination_suspected', 'omission_suspected', 'consensus_mismatch', 'ner_validation_failed', 'schema_validation_failed', 'manual_flag', name='hitl_reason'), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'in_review', 'resolved', 'dismissed', name='hitl_status'), server_default='pending', nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_facing_message', sa.String(length=512), nullable=False),
    sa.Column('assigned_admin_id', sa.UUID(), nullable=True),
    sa.Column('resolved_by_id', sa.UUID(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_hitl_queue_appointment_id_appointments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigned_admin_id'], ['users.id'], name=op.f('fk_hitl_queue_assigned_admin_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['entity_set_id'], ['extracted_entity_sets.id'], name=op.f('fk_hitl_queue_entity_set_id_extracted_entity_sets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], name=op.f('fk_hitl_queue_resolved_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], name=op.f('fk_hitl_queue_transcript_id_transcripts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hitl_queue'))
    )
    op.create_index(op.f('ix_hitl_queue_appointment_id'), 'hitl_queue', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_hitl_queue_reason'), 'hitl_queue', ['reason'], unique=False)
    op.create_index(op.f('ix_hitl_queue_status'), 'hitl_queue', ['status'], unique=False)
    op.create_table('intake_forms',
    sa.Column('appointment_id', sa.UUID(), nullable=False),
    sa.Column('nurse_id', sa.UUID(), nullable=False),
    sa.Column('source_entity_set_id', sa.UUID(), nullable=True),
    sa.Column('input_source', postgresql.ENUM('manual_entry', 'live_recording', 'uploaded_audio', name='input_source'), nullable=False),
    sa.Column('form_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('supersedes_id', sa.UUID(), nullable=True),
    sa.Column('edited_by_id', sa.UUID(), nullable=True),
    sa.Column('is_final', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_intake_forms_appointment_id_appointments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['edited_by_id'], ['users.id'], name=op.f('fk_intake_forms_edited_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['nurse_id'], ['users.id'], name=op.f('fk_intake_forms_nurse_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_entity_set_id'], ['extracted_entity_sets.id'], name=op.f('fk_intake_forms_source_entity_set_id_extracted_entity_sets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supersedes_id'], ['intake_forms.id'], name=op.f('fk_intake_forms_supersedes_id_intake_forms'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intake_forms'))
    )
    op.create_index(op.f('ix_intake_forms_appointment_id'), 'intake_forms', ['appointment_id'], unique=False)
    op.create_table('prescriptions',
    sa.Column('appointment_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('source_entity_set_id', sa.UUID(), nullable=True),
    sa.Column('input_source', postgresql.ENUM('manual_entry', 'live_recording', 'uploaded_audio', name='input_source'), nullable=False),
    sa.Column('form_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('supersedes_id', sa.UUID(), nullable=True),
    sa.Column('edited_by_id', sa.UUID(), nullable=True),
    sa.Column('is_final', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pdf_storage_path', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_prescriptions_appointment_id_appointments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], name=op.f('fk_prescriptions_doctor_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['edited_by_id'], ['users.id'], name=op.f('fk_prescriptions_edited_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_entity_set_id'], ['extracted_entity_sets.id'], name=op.f('fk_prescriptions_source_entity_set_id_extracted_entity_sets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supersedes_id'], ['prescriptions.id'], name=op.f('fk_prescriptions_supersedes_id_prescriptions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prescriptions'))
    )
    op.create_index(op.f('ix_prescriptions_appointment_id'), 'prescriptions', ['appointment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prescriptions_appointment_id'), table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_index(op.f('ix_intake_forms_appointment_id'), table_name='intake_forms')
    op.drop_table('intake_forms')
    op.drop_index(op.f('ix_hitl_queue_status'), table_name='hitl_queue')
    op.drop_index(op.f('ix_hitl_queue_reason'), table_name='hitl_queue')
    op.drop_index(op.f('ix_hitl_queue_appointment_id'), table_name='hitl_queue')
    op.drop_table('hitl_queue')
    op.drop_index(op.f('ix_extracted_entity_sets_transcript_id'), table_name='extracted_entity_sets')
    op.drop_index(op.f('ix_extracted_entity_sets_appointment_id'), table_name='extracted_entity_sets')
    op.drop_table('extracted_entity_sets')
    op.drop_index(op.f('ix_transcripts_status'), table_name='transcripts')
    op.drop_index(op.f('ix_transcripts_audio_chunk_id'), table_name='transcripts')
    op.drop_index(op.f('ix_transcripts_appointment_id'), table_name='transcripts')
    op.drop_table('transcripts')
    op.drop_index(op.f('ix_audio_chunks_audio_recording_id'), table_name='audio_chunks')
    op.drop_table('audio_chunks')
    op.drop_index(op.f('ix_audio_recordings_sha256_hash'), table_name='audio_recordings')
    op.drop_index(op.f('ix_audio_recordings_processing_status'), table_name='audio_recordings')
    op.drop_index(op.f('ix_audio_recordings_appointment_id'), table_name='audio_recordings')
    op.drop_table('audio_recordings')
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_nurse_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_doctor_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_patients_mrn'), table_name='patients')
    op.drop_index(op.f('ix_patients_full_name'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_audit_logs_target_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_target_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_occurred_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
